/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.aiderezo;

import java.awt.Color;

/**
 *
 * @author Hp
 */
public class jClass extends javax.swing.JPanel {

    /**
     * Creates new form jClass
     */
    public jClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPoint1 = new javax.swing.JLabel();
        jTextFieldIP3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonClass = new javax.swing.JButton();
        jLabelClassReponse = new javax.swing.JLabel();
        jTextFieldIP1 = new javax.swing.JTextField();
        jLabelPoint4 = new javax.swing.JLabel();
        jTextFieldIP4 = new javax.swing.JTextField();
        jTextFieldIP2 = new javax.swing.JTextField();
        jLabelPoint5 = new javax.swing.JLabel();

        jLabelPoint1.setText(".");

        jTextFieldIP3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP3CaretUpdate(evt);
            }
        });

        jLabel2.setText("IP :");

        jButtonClass.setText("Class");
        jButtonClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClassMouseClicked(evt);
            }
        });
        jButtonClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassActionPerformed(evt);
            }
        });
        jButtonClass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonClassKeyPressed(evt);
            }
        });

        jTextFieldIP1.setToolTipText("3");
        jTextFieldIP1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP1CaretUpdate(evt);
            }
        });

        jLabelPoint4.setText(".");

        jTextFieldIP4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP4CaretUpdate(evt);
            }
        });

        jTextFieldIP2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP2CaretUpdate(evt);
            }
        });

        jLabelPoint5.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelClassReponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIP1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPoint1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIP2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPoint4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIP3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPoint5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIP4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButtonClass, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPoint1)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPoint4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPoint5))
                    .addComponent(jTextFieldIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClassReponse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClassMouseClicked

        if (jTextFieldIP1 != null & jTextFieldIP2 != null & jTextFieldIP3 != null & jTextFieldIP4 != null) {//test pour jTextFieldIP

            try {//je test si les  jTextFieldIP son des entier (l 189, l 210, l 215, l 220)
                Integer IP = Integer.parseInt(jTextFieldIP1.getText());//j'implemente dans la variable IP se qu'il se trouve dans jTextFieldIP1
                if (IP <= 255 & IP >= 0) {//entre 0 et 255 compris on fait les test sinon ligne 205
                    if (IP >= 0 & IP <= 127) {//entre 0 et 127 compris class A
                        jLabelClassReponse.setText("Class : A");
                    } else if (IP >= 128 & IP <= 191) {//entre 128 et 191 compris class B
                        jLabelClassReponse.setText("Class : B");
                    } else if (IP >= 192 & IP <= 223) {// entre 192 et 223 compris class C
                        jLabelClassReponse.setText("Class : C");
                    } else if (IP >= 224 & IP <= 239) {//entre 224 et 239 compris class D
                        jLabelClassReponse.setText("Class : D");
                    } else if (IP >= 240) {// AU dessus de 240 compris class E
                        jLabelClassReponse.setText("Class : E");
                    }

                } else {
                    jLabelClassReponse.setText("Premiere case non coprise entre 0 et 255");
                }
            } catch (Exception e) {
                jLabelClassReponse.setText("Erreur dans la case 1 de IP");
            }
            try {
                Integer IP = Integer.parseInt(jTextFieldIP2.getText());
            } catch (Exception e) {
                jLabelClassReponse.setText("Erreur dans la case 2 de IP");
            }
            try {
                Integer IP = Integer.parseInt(jTextFieldIP3.getText());
            } catch (Exception e) {
                jLabelClassReponse.setText("Erreur dans la case 3 de IP");
            }
            try {
                Integer IP = Integer.parseInt(jTextFieldIP4.getText());
            } catch (Exception e) {
                jLabelClassReponse.setText("Erreur dans la case 4 de IP");
            }
        } else {
            jLabelClassReponse.setText("Veuillez remplir toute les case");
        }
    }//GEN-LAST:event_jButtonClassMouseClicked

    private void jButtonClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClassActionPerformed

    private void jButtonClassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonClassKeyPressed

    }//GEN-LAST:event_jButtonClassKeyPressed

    private void jTextFieldIP1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP1CaretUpdate
        if (jTextFieldIP1.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP1.getText()) > 255) {
            jTextFieldIP1.setForeground(Color.red);
        } else {
            jTextFieldIP1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP1CaretUpdate

    private void jTextFieldIP2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP2CaretUpdate
        if (jTextFieldIP2.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP2.getText()) > 255) {
            jTextFieldIP2.setForeground(Color.red);
        } else {
            jTextFieldIP2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP2CaretUpdate

    private void jTextFieldIP3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP3CaretUpdate
        if (jTextFieldIP3.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP3.getText()) > 255) {
            jTextFieldIP3.setForeground(Color.red);
        } else {
            jTextFieldIP3.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP3CaretUpdate

    private void jTextFieldIP4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP4CaretUpdate
        if (jTextFieldIP4.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP4.getText()) > 255) {
            jTextFieldIP4.setForeground(Color.red);
        } else {
            jTextFieldIP4.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP4CaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelClassReponse;
    private javax.swing.JLabel jLabelPoint1;
    private javax.swing.JLabel jLabelPoint4;
    private javax.swing.JLabel jLabelPoint5;
    private javax.swing.JTextField jTextFieldIP1;
    private javax.swing.JTextField jTextFieldIP2;
    private javax.swing.JTextField jTextFieldIP3;
    private javax.swing.JTextField jTextFieldIP4;
    // End of variables declaration//GEN-END:variables
}
