/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycompany.aiderezo;

import java.awt.Color;

/**
 *
 * @author v.marques
 */
public class jPing extends javax.swing.JPanel {

    /**
     * Creates new form jPing
     */
    public jPing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldMasque6 = new javax.swing.JTextField();
        jTextFieldMasque7 = new javax.swing.JTextField();
        jLabelPoint13 = new javax.swing.JLabel();
        jLabelPoint8 = new javax.swing.JLabel();
        jTextFieldIP6 = new javax.swing.JTextField();
        jTextFieldIP7 = new javax.swing.JTextField();
        jTextFieldIP8 = new javax.swing.JTextField();
        jTextFieldMasque4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonSousReseau = new javax.swing.JButton();
        jTextFieldMasque8 = new javax.swing.JTextField();
        jLabelPoint6 = new javax.swing.JLabel();
        jLabelPoint7 = new javax.swing.JLabel();
        jTextFieldIP1 = new javax.swing.JTextField();
        jTextFieldMasque3 = new javax.swing.JTextField();
        jLabelPoint4 = new javax.swing.JLabel();
        jLabelPoint1 = new javax.swing.JLabel();
        jLabelPoint9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelPoint2 = new javax.swing.JLabel();
        jLabelTestPing = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIP4 = new javax.swing.JTextField();
        jLabelPoint11 = new javax.swing.JLabel();
        jTextFieldMasque2 = new javax.swing.JTextField();
        jTextFieldMasque1 = new javax.swing.JTextField();
        jTextFieldIP5 = new javax.swing.JTextField();
        jLabelPoint10 = new javax.swing.JLabel();
        jLabelPoint12 = new javax.swing.JLabel();
        jTextFieldIP3 = new javax.swing.JTextField();
        jTextFieldMasque5 = new javax.swing.JTextField();
        jTextFieldIP2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelPoint5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextFieldMasque6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque6CaretUpdate(evt);
            }
        });

        jTextFieldMasque7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque7CaretUpdate(evt);
            }
        });

        jLabelPoint13.setText(".");

        jLabelPoint8.setText(".");

        jTextFieldIP6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP6CaretUpdate(evt);
            }
        });

        jTextFieldIP7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP7CaretUpdate(evt);
            }
        });

        jTextFieldIP8.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP8CaretUpdate(evt);
            }
        });

        jTextFieldMasque4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque4CaretUpdate(evt);
            }
        });

        jLabel4.setText("IP :");

        jButtonSousReseau.setText("Claculer");
        jButtonSousReseau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSousReseauMouseClicked(evt);
            }
        });
        jButtonSousReseau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSousReseauActionPerformed(evt);
            }
        });
        jButtonSousReseau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSousReseauKeyPressed(evt);
            }
        });

        jTextFieldMasque8.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque8CaretUpdate(evt);
            }
        });

        jLabelPoint6.setText(".");

        jLabelPoint7.setText(".");

        jTextFieldIP1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP1CaretUpdate(evt);
            }
        });

        jTextFieldMasque3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque3CaretUpdate(evt);
            }
        });

        jLabelPoint4.setText(".");

        jLabelPoint1.setText(".");

        jLabelPoint9.setText(".");

        jLabel5.setText("Masque :");

        jLabelPoint2.setText(".");

        jLabelTestPing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IP 1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("IP 2");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldIP4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP4CaretUpdate(evt);
            }
        });

        jLabelPoint11.setText(".");

        jTextFieldMasque2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque2CaretUpdate(evt);
            }
        });

        jTextFieldMasque1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque1CaretUpdate(evt);
            }
        });

        jTextFieldIP5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP5CaretUpdate(evt);
            }
        });

        jLabelPoint10.setText(".");

        jLabelPoint12.setText(".");

        jTextFieldIP3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP3CaretUpdate(evt);
            }
        });

        jTextFieldMasque5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque5CaretUpdate(evt);
            }
        });

        jTextFieldIP2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP2CaretUpdate(evt);
            }
        });

        jLabel2.setText("IP :");

        jLabelPoint5.setText(".");

        jLabel3.setText("Masque :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelTestPing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldMasque5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIP5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPoint13)
                                    .addComponent(jLabelPoint9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldIP6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMasque6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPoint12)
                                    .addComponent(jLabelPoint6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldIP7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMasque7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPoint8)
                                    .addComponent(jLabelPoint2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIP8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMasque8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonSousReseau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldIP1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMasque1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPoint7)
                                    .addComponent(jLabelPoint1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldIP2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMasque2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPoint10)
                                    .addComponent(jLabelPoint4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldMasque3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIP3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelPoint11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMasque4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelPoint5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldIP4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMasque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint7)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMasque2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint10)
                            .addComponent(jTextFieldMasque3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint11)
                            .addComponent(jTextFieldMasque4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPoint5)
                        .addComponent(jTextFieldIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabelPoint9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPoint6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldIP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMasque5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMasque7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint8)
                            .addComponent(jTextFieldMasque6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint12)
                            .addComponent(jLabelPoint13)
                            .addComponent(jTextFieldMasque8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldIP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSousReseau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTestPing, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMasque6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque6CaretUpdate
                 if (jTextFieldMasque6.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque6.getText())>255 ) {
            jTextFieldMasque6.setForeground(Color.red);
        } else {
           jTextFieldMasque6.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque6CaretUpdate

    private void jTextFieldMasque7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque7CaretUpdate
                 if (jTextFieldMasque7.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque7.getText())>255 ) {
            jTextFieldMasque7.setForeground(Color.red);
        } else {
            jTextFieldMasque7.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque7CaretUpdate

    private void jTextFieldIP6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP6CaretUpdate
                 if (jTextFieldIP6.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP6.getText())>255 ) {
           jTextFieldIP6.setForeground(Color.red);
        } else {
           jTextFieldIP6.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP6CaretUpdate

    private void jTextFieldIP7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP7CaretUpdate
                 if (jTextFieldIP7.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP7.getText())>255 ) {
            jTextFieldIP7.setForeground(Color.red);
        } else {
            jTextFieldIP7.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP7CaretUpdate

    private void jTextFieldIP8CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP8CaretUpdate
                 if (jTextFieldIP8.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP8.getText())>255 ) {
            jTextFieldIP8.setForeground(Color.red);
        } else {
            jTextFieldIP8.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP8CaretUpdate

    private void jTextFieldMasque4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque4CaretUpdate
                 if (jTextFieldMasque4.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque4.getText())>255 ) {
            jTextFieldMasque4.setForeground(Color.red);
        } else {
            jTextFieldMasque4.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque4CaretUpdate

    private void jButtonSousReseauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSousReseauMouseClicked

    }//GEN-LAST:event_jButtonSousReseauMouseClicked

    private void jButtonSousReseauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSousReseauActionPerformed
        if (!empty(jTextFieldIP1.getText()) & !empty(jTextFieldIP2.getText()) & !empty(jTextFieldIP3.getText())& !empty(jTextFieldIP4.getText()) // on verifie si les jText ne sont pas vide
            & jTextFieldMasque1.getText() != null & jTextFieldMasque2.getText() != null & jTextFieldMasque3.getText() != null & jTextFieldMasque4.getText() != null) {

            Integer IP1 = Integer.parseInt(jTextFieldIP1.getText());
            Integer IP2 = Integer.parseInt(jTextFieldIP2.getText());
            Integer IP3 = Integer.parseInt(jTextFieldIP3.getText());
            Integer IP4 = Integer.parseInt(jTextFieldIP4.getText());
            Integer IP5 = Integer.parseInt(jTextFieldIP5.getText());
            Integer IP6 = Integer.parseInt(jTextFieldIP6.getText());
            Integer IP7 = Integer.parseInt(jTextFieldIP7.getText());
            Integer IP8 = Integer.parseInt(jTextFieldIP8.getText());

            Integer Masque1 = Integer.parseInt(jTextFieldMasque1.getText());
            Integer Masque2 = Integer.parseInt(jTextFieldMasque2.getText());
            Integer Masque3 = Integer.parseInt(jTextFieldMasque3.getText());
            Integer Masque4 = Integer.parseInt(jTextFieldMasque4.getText());
            Integer Masque5 = Integer.parseInt(jTextFieldMasque5.getText());
            Integer Masque6 = Integer.parseInt(jTextFieldMasque6.getText());
            Integer Masque7 = Integer.parseInt(jTextFieldMasque7.getText());
            Integer Masque8 = Integer.parseInt(jTextFieldMasque8.getText());

            String IPReseau1 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP1 & Masque1), 2));
            String IPReseau2 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP2 & Masque2), 2));
            String IPReseau3 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP3 & Masque3), 2));
            String IPReseau4 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP4 & Masque4), 2));
            String IPReseau5 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP5 & Masque5), 2));
            String IPReseau6 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP6 & Masque6), 2));
            String IPReseau7 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP7 & Masque7), 2));
            String IPReseau8 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP8 & Masque8), 2));

            String testIP1=(IPReseau1 + "." + IPReseau2 + "." + IPReseau3 + "." + IPReseau4);
            String testIP2=(IPReseau5 + "." + IPReseau6 + "." + IPReseau7 + "." + IPReseau8);

            //verification du masque
            Integer jtabMasque[] = {Masque1, Masque2, Masque3, Masque4, Masque5, Masque6, Masque7, Masque8};
            Integer i = 0;
            while (i < 9) {
                if (jtabMasque[i] == 255 || jtabMasque[i] == 254|| jtabMasque[i] == 252|| jtabMasque[i] == 248|| jtabMasque[i] == 240|| jtabMasque[i] == 224|| jtabMasque[i] == 196|| jtabMasque[i] == 128 || jtabMasque[i] == 0) {
                    if (testIP1.equals(testIP2)) {
                        jLabelTestPing.setText("Les 2 IP peuvent communiquer");
                    }else{
                        jLabelTestPing.setText("Impossible de faire communiquer les 2 IP");
                    }

                    i++;
                }else{
                                        jLabelTestPing.setText("Erreur Masque Impossible case "+(i+1));
                    i++;
                }

            }
        }else{jLabelTestPing.setText("il manque un champs de saisie");}
        System.out.println("probleme");
    }//GEN-LAST:event_jButtonSousReseauActionPerformed

    private void jButtonSousReseauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSousReseauKeyPressed

    }//GEN-LAST:event_jButtonSousReseauKeyPressed

    private void jTextFieldMasque8CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque8CaretUpdate
        if (jTextFieldMasque8.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque8.getText())>255 ) {
            jTextFieldMasque8.setForeground(Color.red);
        } else {
            jTextFieldMasque8.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque8CaretUpdate

    private void jTextFieldIP1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP1CaretUpdate
        if (jTextFieldIP1.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP1.getText())>255 ) {
            jTextFieldIP1.setForeground(Color.red);
        } else {
            jTextFieldIP1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP1CaretUpdate

    private void jTextFieldMasque3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque3CaretUpdate
        if (jTextFieldMasque3.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque3.getText())>255 ) {
            jTextFieldMasque3.setForeground(Color.red);
        } else {
            jTextFieldMasque3.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque3CaretUpdate

    private void jTextFieldIP4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP4CaretUpdate
        if (jTextFieldIP4.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP4.getText())>255 ) {
            jTextFieldIP4.setForeground(Color.red);
        } else {
            jTextFieldIP4.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP4CaretUpdate

    private void jTextFieldMasque2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque2CaretUpdate
        if (jTextFieldMasque2.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque2.getText())>255 ) {
            jTextFieldMasque2.setForeground(Color.red);
        } else {
            jTextFieldMasque2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque2CaretUpdate

    private void jTextFieldMasque1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque1CaretUpdate
        if (jTextFieldMasque1.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque1.getText())>255 ) {
            jTextFieldMasque1.setForeground(Color.red);
        } else {
            jTextFieldMasque1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque1CaretUpdate

    private void jTextFieldIP5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP5CaretUpdate
                if (jTextFieldIP5.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP5.getText())>255 ) {
            jTextFieldIP5.setForeground(Color.red);
        } else {
            jTextFieldIP5.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP5CaretUpdate

    private void jTextFieldIP3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP3CaretUpdate
        if (jTextFieldIP3.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP3.getText())>255 ) {
            jTextFieldIP3.setForeground(Color.red);
        } else {
            jTextFieldIP3.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP3CaretUpdate

    private void jTextFieldMasque5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque5CaretUpdate
                if (jTextFieldMasque5.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque5.getText())>255 ) {
            jTextFieldMasque5.setForeground(Color.red);
        } else {
            jTextFieldMasque5.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque5CaretUpdate

    private void jTextFieldIP2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP2CaretUpdate
        if (jTextFieldIP2.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP2.getText())>255 ) {
            jTextFieldIP2.setForeground(Color.red);
        } else {
            jTextFieldIP2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP2CaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSousReseau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPoint1;
    private javax.swing.JLabel jLabelPoint10;
    private javax.swing.JLabel jLabelPoint11;
    private javax.swing.JLabel jLabelPoint12;
    private javax.swing.JLabel jLabelPoint13;
    private javax.swing.JLabel jLabelPoint2;
    private javax.swing.JLabel jLabelPoint4;
    private javax.swing.JLabel jLabelPoint5;
    private javax.swing.JLabel jLabelPoint6;
    private javax.swing.JLabel jLabelPoint7;
    private javax.swing.JLabel jLabelPoint8;
    private javax.swing.JLabel jLabelPoint9;
    private javax.swing.JLabel jLabelTestPing;
    private javax.swing.JTextField jTextFieldIP1;
    private javax.swing.JTextField jTextFieldIP2;
    private javax.swing.JTextField jTextFieldIP3;
    private javax.swing.JTextField jTextFieldIP4;
    private javax.swing.JTextField jTextFieldIP5;
    private javax.swing.JTextField jTextFieldIP6;
    private javax.swing.JTextField jTextFieldIP7;
    private javax.swing.JTextField jTextFieldIP8;
    private javax.swing.JTextField jTextFieldMasque1;
    private javax.swing.JTextField jTextFieldMasque2;
    private javax.swing.JTextField jTextFieldMasque3;
    private javax.swing.JTextField jTextFieldMasque4;
    private javax.swing.JTextField jTextFieldMasque5;
    private javax.swing.JTextField jTextFieldMasque6;
    private javax.swing.JTextField jTextFieldMasque7;
    private javax.swing.JTextField jTextFieldMasque8;
    // End of variables declaration//GEN-END:variables

    private boolean empty(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
