package mycompany.aiderezo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author Hp
 */
public class jSousReseau extends javax.swing.JPanel {

    /**
     * Creates new form SousReseau
     */
    public jSousReseau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldMasque3 = new javax.swing.JTextField();
        jLabelPoint1 = new javax.swing.JLabel();
        jLabelPoint11 = new javax.swing.JLabel();
        jTextFieldMasque1 = new javax.swing.JTextField();
        jTextFieldIP3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMasque4 = new javax.swing.JTextField();
        jButtonSousReseau = new javax.swing.JButton();
        jLabelPoint7 = new javax.swing.JLabel();
        jTextFieldIP1 = new javax.swing.JTextField();
        jLabelPoint4 = new javax.swing.JLabel();
        jTextFieldIP4 = new javax.swing.JTextField();
        jTextFieldMasque2 = new javax.swing.JTextField();
        jLabelPoint10 = new javax.swing.JLabel();
        jTextFieldIP2 = new javax.swing.JTextField();
        jLabelPoint5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListIP = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelNBIPDispo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelIPReseau = new javax.swing.JLabel();

        jTextFieldMasque3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque3CaretUpdate(evt);
            }
        });

        jLabelPoint1.setText(".");

        jLabelPoint11.setText(".");

        jTextFieldMasque1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque1CaretUpdate(evt);
            }
        });

        jTextFieldIP3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP3CaretUpdate(evt);
            }
        });

        jLabel2.setText("IP :");

        jLabel3.setText("Masque :");

        jTextFieldMasque4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque4CaretUpdate(evt);
            }
        });

        jButtonSousReseau.setText("Claculer");
        jButtonSousReseau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSousReseauMouseClicked(evt);
            }
        });
        jButtonSousReseau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSousReseauActionPerformed(evt);
            }
        });
        jButtonSousReseau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSousReseauKeyPressed(evt);
            }
        });

        jLabelPoint7.setText(".");

        jTextFieldIP1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP1CaretUpdate(evt);
            }
        });

        jLabelPoint4.setText(".");

        jTextFieldIP4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP4CaretUpdate(evt);
            }
        });

        jTextFieldMasque2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldMasque2CaretUpdate(evt);
            }
        });

        jLabelPoint10.setText(".");

        jTextFieldIP2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIP2CaretUpdate(evt);
            }
        });

        jLabelPoint5.setText(".");

        jListIP.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListIP.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jListIP);

        jLabel1.setText("Nombre ip dispo :");

        jLabel4.setText("Ip reseau :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldIP1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldMasque1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPoint7)
                                            .addComponent(jLabelPoint1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldIP2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldMasque2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPoint10)
                                            .addComponent(jLabelPoint4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldMasque3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldIP3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelPoint11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldMasque4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelPoint5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldIP4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelNBIPDispo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSousReseau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelIPReseau, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMasque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint7)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMasque2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint10)
                            .addComponent(jTextFieldMasque3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPoint11)
                            .addComponent(jTextFieldMasque4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPoint5)
                        .addComponent(jTextFieldIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSousReseau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNBIPDispo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIPReseau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSousReseauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSousReseauMouseClicked

    }//GEN-LAST:event_jButtonSousReseauMouseClicked

    private void jButtonSousReseauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSousReseauActionPerformed
        if (jTextFieldIP1 != null & jTextFieldIP2 != null & jTextFieldIP3 != null & jTextFieldIP4 != null // on verifie si les jText ne sont pas vide
                & jTextFieldMasque1 != null & jTextFieldMasque2 != null & jTextFieldMasque3 != null & jTextFieldMasque4 != null) {
            
            Integer IP1 = Integer.parseInt(jTextFieldIP1.getText());
            Integer IP2 = Integer.parseInt(jTextFieldIP2.getText());
            Integer IP3 = Integer.parseInt(jTextFieldIP3.getText());
            Integer IP4 = Integer.parseInt(jTextFieldIP4.getText());

            Integer Masque1 = Integer.parseInt(jTextFieldMasque1.getText());
            Integer Masque2 = Integer.parseInt(jTextFieldMasque2.getText());
            Integer Masque3 = Integer.parseInt(jTextFieldMasque3.getText());
            Integer Masque4 = Integer.parseInt(jTextFieldMasque4.getText());

            String IPReseau1 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP1 & Masque1), 2));
            String IPReseau2 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP2 & Masque2), 2));
            String IPReseau3 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP3 & Masque3), 2));
            String IPReseau4 = String.valueOf(Integer.parseInt(Integer.toBinaryString(IP4 & Masque4), 2));
            
            jLabelIPReseau.setText(IPReseau1 + "." + IPReseau2 + "." + IPReseau3 + "." + IPReseau4);
            System.out.println(Integer.toBinaryString(IP1 & Masque1) + "." + Integer.toBinaryString(IP2 & Masque2) + "." + Integer.toBinaryString(IP3 & Masque3) + "." + Integer.toBinaryString(IP4 & Masque4));

            
            //verification du masque
            Integer jtabMasque[] = {Masque1, Masque2, Masque3, Masque4};
            Integer i = 0;
            while (i < 4) {
                if (jtabMasque[i] == 255 || jtabMasque[i] == 254|| jtabMasque[i] == 252|| jtabMasque[i] == 248|| jtabMasque[i] == 240|| jtabMasque[i] == 224|| jtabMasque[i] == 196|| jtabMasque[i] == 128 || jtabMasque[i] == 0) {
                i++;
            }else{
                    jLabelIPReseau.setText("Erreur Masque Impossible case "+(i+1));
                    i++;
                }
                
        }
        }
    }//GEN-LAST:event_jButtonSousReseauActionPerformed

    private void jButtonSousReseauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSousReseauKeyPressed

    }//GEN-LAST:event_jButtonSousReseauKeyPressed

    private void jTextFieldIP1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP1CaretUpdate
         if (jTextFieldIP1.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP1.getText())>255 ) {
            jTextFieldIP1.setForeground(Color.red);
        } else {
            jTextFieldIP1.setForeground(Color.BLACK);
        }
         
    }//GEN-LAST:event_jTextFieldIP1CaretUpdate

    private void jTextFieldIP2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP2CaretUpdate
        if (jTextFieldIP2.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP2.getText())>255 ) {
            jTextFieldIP2.setForeground(Color.red);
        } else {
            jTextFieldIP2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP2CaretUpdate

    private void jTextFieldIP3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP3CaretUpdate
        if (jTextFieldIP3.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP3.getText())>255 ) {
            jTextFieldIP3.setForeground(Color.red);
        } else {
            jTextFieldIP3.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP3CaretUpdate

    private void jTextFieldIP4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIP4CaretUpdate
        if (jTextFieldIP4.getCaretPosition() > 3 || Integer.parseInt(jTextFieldIP4.getText())>255 ) {
            jTextFieldIP4.setForeground(Color.red);
        } else {
            jTextFieldIP4.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldIP4CaretUpdate

    private void jTextFieldMasque1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque1CaretUpdate
       if (jTextFieldMasque1.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque1.getText())>255 ) {
            jTextFieldMasque1.setForeground(Color.red);
        } else {
            jTextFieldMasque1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque1CaretUpdate

    private void jTextFieldMasque2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque2CaretUpdate
        if (jTextFieldMasque2.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque2.getText())>255 ) {
            jTextFieldMasque2.setForeground(Color.red);
        } else {
            jTextFieldMasque2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque2CaretUpdate

    private void jTextFieldMasque3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque3CaretUpdate
        if (jTextFieldMasque3.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque3.getText())>255 ) {
            jTextFieldMasque3.setForeground(Color.red);
        } else {
            jTextFieldMasque3.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque3CaretUpdate

    private void jTextFieldMasque4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldMasque4CaretUpdate
        if (jTextFieldMasque4.getCaretPosition() > 3 || Integer.parseInt(jTextFieldMasque4.getText())>255 ) {
            jTextFieldMasque4.setForeground(Color.red);
        } else {
            jTextFieldMasque4.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldMasque4CaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSousReseau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelIPReseau;
    private javax.swing.JLabel jLabelNBIPDispo;
    private javax.swing.JLabel jLabelPoint1;
    private javax.swing.JLabel jLabelPoint10;
    private javax.swing.JLabel jLabelPoint11;
    private javax.swing.JLabel jLabelPoint4;
    private javax.swing.JLabel jLabelPoint5;
    private javax.swing.JLabel jLabelPoint7;
    private javax.swing.JList<String> jListIP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldIP1;
    private javax.swing.JTextField jTextFieldIP2;
    private javax.swing.JTextField jTextFieldIP3;
    private javax.swing.JTextField jTextFieldIP4;
    private javax.swing.JTextField jTextFieldMasque1;
    private javax.swing.JTextField jTextFieldMasque2;
    private javax.swing.JTextField jTextFieldMasque3;
    private javax.swing.JTextField jTextFieldMasque4;
    // End of variables declaration//GEN-END:variables
}
